// The Makers of the Harvest — Berlin Chili Fest press catalogue.
// Ported from the press-catalogue artifact (aaabb205). Editorial copy is the
// makers' own / festival press copy. Photos: Berlin Chili Fest, editorial use with credit.

export type MakerTrack = "Flavour" | "Seed to Sauce" | "Hyperlocal";
export const MAKER_TRACKS: MakerTrack[] = ["Flavour", "Seed to Sauce", "Hyperlocal"];

export interface Maker {
  id: string;
  name: string;
  legalName: string;
  maker: string;
  location: string;
  track: MakerTrack;
  flagship: string;
  heat: string;
  awards: string;
  story: string;
  angles: string[];
  photo: string | null;
}

export const MAKERS: Maker[] = [
  {
    id: "instant-taste",
    name: "Instant Taste",
    legalName: "· Instant Upgrade Spices",
    maker: "Martina Wastl",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Chimichurri Crisp",
    heat: "1–2/10",
    awards: "",
    story: "An Austrian in Berlin took chimichurri, the green herb sauce Argentines argue over, and made it crunchy: a chilli oil you spoon for the flavour, not the burn.",
    angles: ["An Austrian who moved to Berlin, reworking Argentina's chimichurri into a jar.", "The crunchy chilli-oil boom, but herb-led and low-heat for the flavour crowd.", "A spoonable oil built for texture and flavour over burn. Contains almonds."],
    photo: "/chilifest/makers/instant-taste.jpg",
  },
  {
    id: "luchadoras-del-sabor",
    name: "Luchadoras del Sabor",
    legalName: "· La Tiendita",
    maker: "Max Weiss",
    location: "Kreuzberg / Neukölln, Berlin",
    track: "Flavour",
    flagship: "La Quebradora (salsa verde)",
    heat: "1–3/10",
    awards: "",
    story: "For thirty years a Vienna-born Neukölln cook made salsa only for the friends who kept telling him to sell it. He finally has: three salsas, each named after a lucha libre wrestling move.",
    angles: ["A Vienna-born, decades-in-Neukölln cook who finally bottled the salsas he made for friends.", "Lucha-libre branding on authentic Oaxacan-style salsa: a story and a visual in one.", "La Quebradora, a fresh tomatillo salsa verde at 1-3/10, the mild one of a three-salsa tag team."],
    photo: "/chilifest/makers/luchadoras-del-sabor.jpg",
  },
  {
    id: "neck-dart",
    name: "Neck-Dart",
    legalName: "",
    maker: "Robert Pierce",
    location: "Kreuzberg, Berlin",
    track: "Flavour",
    flagship: "Garlic Habamayo",
    heat: "2/10",
    awards: "Silver + Bronze · 2025",
    story: "A Berlin sommelier started fermenting habaneros in lockdown and now medals at the European Hot Sauce Awards. His mildest bottle, a vegan garlic chilli mayo, is built to win over the people at the table who swear they hate hot sauce.",
    angles: ["A Berlin sommelier who started fermenting habaneros in lockdown.", "Live-fermented, unpasteurised sauces riding the gut-health wave.", "Garlic Habamayo, a vegan chilli mayo at 2/10 that bridges spice-lovers and avoiders."],
    photo: "/chilifest/makers/neck-dart.jpg",
  },
  {
    id: "queima-beicas",
    name: "Queima Beiças",
    legalName: "",
    maker: "Francisco Silva",
    location: "Madeira, PT",
    track: "Flavour",
    flagship: "Goiaba (guava)",
    heat: "1/10",
    awards: "",
    story: "Madeira is known for fortified wine, not chilli. Francisco Silva bottles the island anyway: guava and sugarcane-honey sauces where the fruit lands first and the heat only signs off at the end.",
    angles: ["A young maker bottling Madeira's own larder, from guava to sugarcane honey.", "Fruit-forward sauces where flavour leads and heat follows, for the adventurous, not the masochist.", "Goiaba, a guava sauce at 1/10, put in a hand with cheese or grilled pork."],
    photo: "/chilifest/makers/queima-beicas.jpg",
  },
  {
    id: "chillipeterson",
    name: "ChilliPeterson",
    legalName: "",
    maker: "Petr Schejbal",
    location: "Ostrava, CZ",
    track: "Flavour",
    flagship: "Zpečený Indián (mild tikka)",
    heat: "",
    awards: "",
    story: "In the Czech steel city of Ostrava, Petr Schejbal bottles chilli sauce with no preservatives. His first one ever, the smoky 'Zpečený Indián', was voted product of the year at the Mechov chilli festival.",
    angles: ["An Ostrava maker bottling preservative-free chilli sauce since 2020.", "Central-European craft chilli, an award-winner out of the Czech steel belt.", "'Zpečený Indián', a mild smoky tikka-style sauce, his first ever and a festival product of the year."],
    photo: "/chilifest/makers/chillipeterson.jpg",
  },
  {
    id: "marie-sharp-s",
    name: "Marie Sharp's",
    legalName: "· Germany · Jürgen Rahm",
    maker: "Jürgen Rahm",
    location: "Herrsching, Bavaria (made in Belize)",
    track: "Flavour",
    flagship: "Mango Pepper",
    heat: "2/10",
    awards: "",
    story: "Marie Sharp built a Belize hot sauce name by replacing the vinegar in the bottle with carrots. Her German champions bring the mango version, the gentlest in the range, to Berlin.",
    angles: ["A German importer championing Marie Sharp's, the Belize brand that swapped vinegar for carrots.", "A heritage-brand story: carrot-and-habanero as the original flavour-first hot sauce.", "Mango Pepper at 2/10, gentle enough for watermelon salad or breakfast cereal."],
    photo: "/chilifest/makers/marie-sharp-s.jpg",
  },
  {
    id: "chiliwerk",
    name: "Chiliwerk",
    legalName: "",
    maker: "Kai Kolipost",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Hot Honey",
    heat: "",
    awards: "Silver · 2025",
    story: "A Berlin maker that took EHSA 2025 Silver for its roasted lemon-habanero sauce wants to lead here with something gentler: a hot honey.",
    angles: ["A Berlin maker spanning citrus-mild to Carolina Reaper, leading with a gentler idea.", "Hot honey, the crossover condiment breaking out of the chilli aisle.", "A hot honey to open with, and the EHSA 2025 Silver lemon-habanero for the heat desk."],
    photo: "/chilifest/makers/chiliwerk.jpg",
  },
  {
    id: "don-cabron",
    name: "Don Cabron",
    legalName: "· Salsas Don Cabron",
    maker: "Karla Carral",
    location: "Rijswijk, NL",
    track: "Flavour",
    flagship: "Salsa Macha, Crispy Chili Oil",
    heat: "",
    awards: "Bronze · 2026",
    story: "A Northern-Mexican cook bottles her family's regional salsas from a base in the Netherlands, bringing salsa macha, Mexico's crispy chilli oil, to Europe just as it takes off.",
    angles: ["A Northern-Mexican cook bottling her family's regional salsas from the Netherlands.", "Salsa macha, Mexico's crispy chilli oil, arriving in Europe as it takes off.", "A crispy salsa macha as the bestseller, for the crunchy-oil crowd."],
    photo: "/chilifest/makers/don-cabron.jpg",
  },
  {
    id: "moja",
    name: "Moja",
    legalName: "· Moja Berlin",
    maker: "Maliha Fairooz",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Chunky Chili Oil",
    heat: "",
    awards: "Bronze · 2026",
    story: "A Berlin chilli oil that blends Bengali spice with, in the maker's own words, Sierra Leonean soul, made by hand by a travel writer who has eaten her way through more than a hundred countries.",
    angles: ["A travel writer who has eaten through 100+ countries, now bottling in Berlin.", "Chunky chilli oil and diaspora flavour: Bengali spice meeting Sierra Leonean influence.", "A vegan chunky chilli oil, made in Original, Hotter and Mango."],
    photo: "/chilifest/makers/moja.jpg",
  },
  {
    id: "not-that-spicy",
    name: "Not That Spicy",
    legalName: "",
    maker: "Justin King",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Princess Passion",
    heat: "",
    awards: "Gold ×3 · 2026",
    story: "The name is the promise: flavour over burn, no extracts. This Berlin maker just took three Golds at the 2026 European Hot Sauce Awards to back it up.",
    angles: ["A Berlin maker who put his whole philosophy in the brand name.", "Flavour over heat, no extracts: the anti-superhot movement, with three 2026 Golds.", "Princess Passion, a flavour-first sauce built for taste, not punishment."],
    photo: "/chilifest/makers/not-that-spicy.jpg",
  },
  {
    id: "qudo-tjes",
    name: "Qudo'tjes",
    legalName: "",
    maker: "Gertjan Caris",
    location: "Valkenswaard, NL",
    track: "Flavour",
    flagship: "Stormur Chili Crisp",
    heat: "",
    awards: "Silver ×2 · 2026",
    story: "A Dutch software developer quit the screen to make hot sauce by hand. His storm-named chilli crisps took two Silvers at the 2026 European Hot Sauce Awards.",
    angles: ["A software developer who quit the screen to make hot sauce by hand.", "Chilli crisp, the category everyone is chasing, with two 2026 EHSA Silvers behind it.", "Stormur, a chilli crisp that leads with flavour and stays mild enough for the German press pack."],
    photo: "/chilifest/makers/qudo-tjes.jpg",
  },
  {
    id: "ti-dodo-epice",
    name: "Ti Dodo Epicé",
    legalName: "· Telfair",
    maker: "Vaanee Stock-Williams",
    location: "Alkmaar, NL",
    track: "Flavour",
    flagship: "Compote Tamarin",
    heat: "2/10",
    awards: "Bronze · 2026",
    story: "Vaanee grew up in Mauritius and missed her mother's cooking when she moved to the Netherlands, so she taught herself to make it. Her Compote Tamarin started as leftovers: the tamarind pulp saved from a hotter sauce, cooked down into the sweet, sticky compote her mum once had to hide from her and her brothers.",
    angles: ["A Mauritian cook in the Netherlands, bottling the sauces and pickles that came with every dish back home.", "Upcycling with flavour: the compote is made from the tamarind pulp left over from her hotter Pima Tamarin sauce.", "Compote Tamarin at 2/10, sweet, sticky and tangy with a chilli finish, as good on vanilla ice cream as on a cheese board."],
    photo: "/chilifest/makers/ti-dodo-epice.jpg",
  },
  {
    id: "momo-haus",
    name: "Momo Haus",
    legalName: "",
    maker: "Biplav Dahal",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Snakebite Chilli Oil",
    heat: "7/10",
    awards: "",
    story: "Every plate of momo at this Berlin restaurant tasted of home except for one thing: the wild Himalayan Timur pepper. Biplav Dahal bottled it as Snakebite Chilli Oil, a first chilli kick followed by the citrusy tingle of Nepal that keeps you reaching back.",
    angles: ["A Berlin momo restaurant bottling the Himalayan Timur pepper that made its food taste of home.", "Timur, the citrus-tingling Himalayan cousin of Sichuan pepper, moving from Nepali kitchens onto shelves.", "Snakebite Chilli Oil at 7/10: a chilli kick first, then the numbing citrus lift of Timur."],
    photo: null,
  },
  {
    id: "teig-fullung",
    name: "Teig & Füllung",
    legalName: "",
    maker: "Bruno Ebermann",
    location: "Berlin (made in Swabia)",
    track: "Seed to Sauce",
    flagship: "Crispy Chili Öl",
    heat: "4/10",
    awards: "",
    story: "A Swabian chef spent a year cooking his way through Asian restaurants and came home hooked on Taiwanese crispy chilli oil. He built his own to crown his family's Maultaschen.",
    angles: ["A Swabian chef who staged across Asian kitchens and built a chilli oil for his own Maultaschen.", "Crispy chilli oil, the format of the moment, from a German maker and not an import.", "Crispy Chili Öl at 4/10, made to lift a plate of handmade Maultaschen."],
    photo: "/chilifest/makers/teig-fullung.jpg",
  },
  {
    id: "harissa-co",
    name: "Harissa & Co",
    legalName: "",
    maker: "Amal Nasri",
    location: "Berlin (made in Cap-Bon, TN)",
    track: "Seed to Sauce",
    flagship: "Spicy Smokey Harissa",
    heat: "",
    awards: "",
    story: "A Berlin-based Tunisian engineer turned her grandmother's recipe into a business built on a single harissa: heirloom Baklouti chillies smoked over olive wood for more than twelve hours.",
    angles: ["A Berlin-based Tunisian engineer building a business on her grandmother's recipe.", "Single-origin, single-product harissa: provenance and heirloom chillies for a slow-food desk.", "One smoked harissa, heirloom Baklouti chillies over olive wood, uncompromisingly hot."],
    photo: null,
  },
  {
    id: "roots-radicals",
    name: "Roots Radicals",
    legalName: "",
    maker: "Cayetana Melero",
    location: "Berlin, DE",
    track: "Seed to Sauce",
    flagship: "Harissa Hot Sauce",
    heat: "",
    awards: "",
    story: "A Berlin producer founded by a molecular biologist turned chef, turning the imperfect produce markets throw away into fermented hot sauces.",
    angles: ["A molecular biologist turned chef running a zero-waste Berlin producer.", "Upcycled, rescued-produce hot sauce: the sustainability angle for a business or eco desk.", "A fermented harissa hot sauce built from the produce markets throw away."],
    photo: null,
  },
  {
    id: "yak-thai",
    name: "Yak Thai",
    legalName: "",
    maker: "Chonticha Schopf",
    location: "Volkenschwand, Bavaria",
    track: "Seed to Sauce",
    flagship: "Thai curry & chili pastes",
    heat: "",
    awards: "",
    story: "A Thai baker who ran her own shop for fifteen years now hand-makes curry and chilli pastes in rural Bavaria, importing her dried chillies from Thailand because Europe's were not good enough.",
    angles: ["A Thai baker who ran her own shop for fifteen years, now making pastes in rural Bavaria.", "Authentic curry and chilli pastes, additive-free, with chillies imported for real flavour.", "Thai curry and chilli pastes rated on her own sharpness scale, made to order."],
    photo: null,
  },
  {
    id: "dr-john-s-hot-sauce",
    name: "Dr. John's Hot Sauce",
    legalName: "",
    maker: "Albert Ortez",
    location: "Nürnberg, Franconia",
    track: "Hyperlocal",
    flagship: "",
    heat: "",
    awards: "",
    story: "An independent hot sauce maker in Nürnberg, sending hand-filled bottles out across Franconia and beyond.",
    angles: ["An independent maker working out of Nürnberg, in Germany's chilli-friendly Franconia.", "Franconia's independent hot sauce scene, for a regional desk.", "Hand-made hot sauce, shipped across Germany."],
    photo: null,
  },
  {
    id: "salsa-boy",
    name: "Salsa Boy",
    legalName: "",
    maker: "Sascha Mayer",
    location: "Berlin, DE",
    track: "Hyperlocal",
    flagship: "",
    heat: "",
    awards: "",
    story: "A one-person Berlin project with a straight face and a bold claim printed on the label: 'Berlin's premium chilli sauce.'",
    angles: ["A one-person Berlin project making a big claim on the label.", "Single-maker premium positioning: 'Berlin's premium chilli sauce'.", "Bottled in small runs in Berlin."],
    photo: null,
  },
];
