// The Makers of the Harvest — Berlin Chili Fest press catalogue.
// Ported from the press-catalogue artifact (aaabb205). Editorial copy is the
// makers' own / festival press copy. Photos: Berlin Chili Fest, editorial use with credit.

export type MakerTrack = "Flavour" | "Seed to Sauce" | "Hyperlocal";
export const MAKER_TRACKS: MakerTrack[] = ["Flavour", "Seed to Sauce", "Hyperlocal"];

export interface Maker {
  id: string;
  name: string;
  legalName: string;
  maker: string;
  location: string;
  track: MakerTrack;
  flagship: string;
  heat: string;
  awards: string;
  story: string;
  angles: string[];
  photo: string | null;
  logo?: string | null;
}

export const MAKERS: Maker[] = [
  {
    id: "instant-taste",
    name: "Instant Taste",
    legalName: "· Instant Upgrade Spices",
    maker: "Martina Wastl",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Chimichurri Crisp",
    heat: "1–2/10",
    awards: "",
    story: "An Austrian in Berlin took chimichurri, the green herb sauce Argentines argue over, and made it crunchy: a chilli oil you spoon for the flavour, not the burn.",
    angles: ["An Austrian who moved to Berlin, reworking Argentina's chimichurri into a jar.", "The crunchy chilli-oil boom, but herb-led and low-heat for the flavour crowd.", "A spoonable oil built for texture and flavour over burn. Contains almonds."],
    photo: "/chilifest/makers/instant-taste.jpg",
  },
  {
    id: "luchadoras-del-sabor",
    name: "Luchadoras del Sabor",
    legalName: "· La Tiendita",
    maker: "Max Weiss",
    location: "Kreuzberg / Neukölln, Berlin",
    track: "Flavour",
    flagship: "La Quebradora (salsa verde)",
    heat: "1–3/10",
    awards: "",
    story: "For thirty years a Vienna-born Neukölln cook made salsa only for the friends who kept telling him to sell it. He finally has: three salsas, each named after a lucha libre wrestling move.",
    angles: ["A Vienna-born, decades-in-Neukölln cook who finally bottled the salsas he made for friends.", "Lucha-libre branding on authentic Oaxacan-style salsa: a story and a visual in one.", "La Quebradora, a fresh tomatillo salsa verde at 1-3/10, the mild one of a three-salsa tag team."],
    photo: "/chilifest/makers/luchadoras-del-sabor.jpg",
  },
  {
    id: "neck-dart",
    name: "Neck-Dart",
    legalName: "",
    maker: "Robert Pierce",
    location: "Kreuzberg, Berlin",
    track: "Flavour",
    flagship: "Garlic Habamayo",
    heat: "2/10",
    awards: "",
    story: "A Berlin sommelier started fermenting habaneros in lockdown. His mildest bottle, a vegan garlic chilli mayo, is built to win over the people at the table who swear they hate hot sauce.",
    angles: ["A Berlin sommelier who started fermenting habaneros in lockdown.", "Live-fermented, unpasteurised sauces riding the gut-health wave.", "Garlic Habamayo, a vegan chilli mayo at 2/10 that bridges spice-lovers and avoiders."],
    photo: "/chilifest/makers/neck-dart.jpg",
  },
  {
    id: "chillipeterson",
    name: "ChilliPeterson",
    legalName: "",
    maker: "Petr Schejbal",
    location: "Ostrava, CZ",
    track: "Flavour",
    flagship: "Zpečený Indián (mild tikka)",
    heat: "",
    awards: "",
    story: "In the Czech steel city of Ostrava, Petr Schejbal bottles chilli sauce with no preservatives. His first one ever, the mild 'Zpečený Indián', is what got the brand off the ground.",
    angles: ["An Ostrava maker bottling preservative-free chilli sauce since 2020.", "Central-European craft chilli out of the Czech steel belt.", "'Zpečený Indián', a mild tikka-style sauce, his first ever."],
    photo: "/chilifest/makers/chillipeterson.jpg",
  },
  {
    id: "marie-sharp-s",
    name: "Marie Sharp's",
    legalName: "· Germany · Jürgen Rahm",
    maker: "Jürgen Rahm",
    location: "Herrsching, Bavaria (made in Belize)",
    track: "Flavour",
    flagship: "Mango Pepper",
    heat: "2/10",
    awards: "",
    story: "Marie Sharp built a Belize hot sauce name by replacing the vinegar in the bottle with carrots. Her German champions bring the mango version, the gentlest in the range, to Berlin.",
    angles: ["A German importer championing Marie Sharp's, the Belize brand that made her a legend after 20 years in Belize.", "A heritage-brand story: carrot-and-habanero as the original flavour-first hot sauce.", "Mango Pepper at 2/10, gentle enough for watermelon salad or breakfast cereal."],
    photo: "/chilifest/makers/marie-sharp-s.jpg",
  },
  {
    id: "chiliwerk",
    name: "Chiliwerk",
    legalName: "",
    maker: "Kai Kolipost",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Hot Honey",
    heat: "",
    awards: "",
    story: "A Berlin maker wants to lead here with something gentler than a sauce: a hot honey.",
    angles: ["A Berlin maker spanning citrus-mild to Carolina Reaper, leading with a gentler idea.", "Hot honey, the crossover condiment breaking out of the chilli aisle.", "A hot honey to open with, and a roasted lemon-habanero for the heat desk."],
    photo: "/chilifest/makers/chiliwerk.jpg",
  },
  {
    id: "don-cabron",
    name: "Don Cabron",
    legalName: "· Salsas Don Cabron",
    maker: "Karla Carral",
    location: "Rijswijk, NL",
    track: "Flavour",
    flagship: "Smoky-Sweet Chili Oil",
    heat: "6/10",
    awards: "Bronze · 2026",
    story: "A Northern-Mexican cook bottles her family's regional salsas from a base in the Netherlands. Her Smoky-Sweet Chili Oil ('Macha Ahumada Dulce') is a traditional crispy macha, deep and smoky from Mexican peppers, with cranberries for sweetness and seeds for crunch.",
    angles: ["A Northern-Mexican cook bottling her family's regional salsas from the Netherlands.", "Smoky-Sweet Chili Oil, a crispy Mexican macha with a deep smoke and a cranberry sweetness, on the crunchy-oil trend.", "Her salsa macha took Bronze at the 2026 European Hot Sauce Awards."],
    photo: "/chilifest/makers/don-cabron.jpg",
  },
  {
    id: "moja",
    name: "Moja",
    legalName: "· Moja Berlin",
    maker: "Maliha Fairooz",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Chunky Chili Oil",
    heat: "",
    awards: "Bronze · 2026",
    story: "A Berlin chilli oil that blends Bengali spice with, in the maker's own words, Sierra Leonean soul, made by hand by a travel writer who has eaten her way through more than a hundred countries.",
    angles: ["A travel writer who has eaten through 100+ countries, now bottling in Berlin.", "Chunky chilli oil and diaspora flavour: Bengali spice meeting Sierra Leonean influence.", "A vegan chunky chilli oil, made in Original, Hotter and Mango."],
    photo: "/chilifest/makers/moja.jpg",
  },
  {
    id: "not-that-spicy",
    name: "Not That Spicy",
    legalName: "",
    maker: "Justin King",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Princess Passion",
    heat: "",
    awards: "Gold ×3 · 2026",
    story: "The name is the promise: flavour over burn, no extracts. This Berlin maker just took three Golds at the 2026 European Hot Sauce Awards to back it up.",
    angles: ["A Berlin maker who put his whole philosophy in the brand name.", "Flavour over heat, no extracts: the anti-superhot movement, with three 2026 Golds.", "Princess Passion, a flavour-first sauce built for taste, not punishment."],
    photo: "/chilifest/makers/not-that-spicy.jpg",
  },
  {
    id: "qudo-tjes",
    name: "Qudo'tjes",
    legalName: "",
    maker: "Gertjan Caris",
    location: "Valkenswaard, NL",
    track: "Flavour",
    flagship: "Stormur Chili Crisp",
    heat: "",
    awards: "Silver ×2 · 2026",
    story: "A Dutch software developer quit the screen to make hot sauce by hand. His storm-named chilli crisps took two Silvers at the 2026 European Hot Sauce Awards.",
    angles: ["A software developer who quit the screen to make hot sauce by hand.", "Chilli crisp, the category everyone is chasing, with two 2026 EHSA Silvers behind it.", "Stormur, a chilli crisp that leads with flavour and stays mild enough for the German press pack."],
    photo: "/chilifest/makers/qudo-tjes.jpg",
  },
  {
    id: "ti-dodo-epice",
    name: "Ti Dodo Epicé",
    legalName: "· Telfair",
    maker: "Vaanee Stock-Williams",
    location: "Alkmaar, NL",
    track: "Flavour",
    flagship: "Compote Tamarin",
    heat: "2/10",
    awards: "Bronze · 2026",
    story: "Vaanee grew up in Mauritius surrounded by its melting-pot cuisine, her mother's cooking most of all, and missed it when she moved to the Netherlands, so she started making it herself. Her Compote Tamarin began as leftovers: tamarind pulp saved from her Pima Tamarin, cooked into the same sticky compote her mum used to hide from her and her brothers.",
    angles: ["A Mauritian small-batch producer in the Netherlands, jarring up the sauces and pickles that came with every dish back home.", "Upcycling with flavour: the compote is made from the tamarind pulp left over from her hot Pima Tamarin sauce.", "Compote Tamarin, 2/10, sweet, sticky and tangy with a chilli finish, as good on vanilla ice cream as on a cheese board."],
    photo: "/chilifest/makers/ti-dodo-epice.jpg",
  },
  {
    id: "momo-haus",
    name: "Momo Haus",
    legalName: "",
    maker: "Biplav Dahal",
    location: "Berlin, DE",
    track: "Flavour",
    flagship: "Snakebite Chilli Oil",
    heat: "7/10",
    awards: "",
    story: "Every plate of momo at this Berlin restaurant tasted of home except for one thing: the wild Himalayan Timur pepper. Biplav Dahal bottled it as Snakebite Chilli Oil, a first chilli kick followed by the citrusy tingle of Nepal that keeps you reaching back.",
    angles: ["A Berlin momo restaurant bottling the Himalayan Timur pepper that made its food taste of home.", "Timur, the citrus-tingling Himalayan cousin of Sichuan pepper, moving from Nepali kitchens onto shelves.", "Snakebite Chilli Oil at 7/10: a chilli kick first, then the tingling citrus lift of Timur."],
    photo: "/chilifest/makers/momo-haus.jpg",
  },
  {
    id: "teig-fullung",
    name: "Teig & Füllung",
    legalName: "",
    maker: "Bruno Ebermann",
    location: "Berlin, DE",
    track: "Seed to Sauce",
    flagship: "Crispy Chili Öl",
    heat: "4/10",
    awards: "",
    story: "A Swabian chef spent a year cooking his way through the kitchens of Taiwan and Hong Kong and came home hooked on crispy chilli oil, so he built his own. It started with his family's Maultaschen but earns its place on dumplings, noodles, rice, even pizza.",
    angles: ["A Swabian chef who staged across Taiwan and Hong Kong and built his own crispy chilli oil back in Germany.", "Crispy chilli oil, the format of the moment, from a German maker and not an import.", "Crispy Chili Öl at 4/10, as good on dumplings, noodles and rice as on handmade Maultaschen."],
    photo: "/chilifest/makers/teig-fullung.jpg",
  },
  {
    id: "harissa-co",
    name: "Harissa & Co",
    legalName: "",
    maker: "Amal Nasri",
    location: "Berlin (made in Cap-Bon, TN)",
    track: "Seed to Sauce",
    flagship: "Spicy Smoky Harissa",
    heat: "3/10",
    awards: "",
    story: "A Berlin-based Tunisian engineer turned her grandmother's recipe into what she calls Germany's first artisanal smoked harissa: heirloom Baklouti chillies smoked over olive wood for more than twelve hours. The '& Co' is the community behind it, the women who passed the recipe down and the farmers who still smoke the Baklouti the old way.",
    angles: ["A Berlin-based Tunisian engineer building a business on her grandmother's recipe and her family's summer harissa-making tradition.", "Single-origin, single-product harissa: heirloom Baklouti chillies smoked over olive wood 12+ hours, for a slow-food or provenance desk.", "One smoked harissa at 3/10, clean-label and full of flavour, for anyone done with watery supermarket paste."],
    photo: "/chilifest/makers/harissa-co.jpg",
  },
  {
    id: "roots-radicals",
    name: "Roots Radicals",
    legalName: "",
    maker: "Mónica Kisic Aguirre",
    location: "Berlin, DE",
    track: "Seed to Sauce",
    flagship: "Fermented Jalapeño",
    heat: "3/10",
    awards: "",
    story: "A Berlin producer founded by Peruvian scientist and chef Mónica Kisic Aguirre, turning the imperfect ingredients markets throw away into bold fermented hot sauces through circular cooking. Their Fermented Jalapeño ferments the chillies for six weeks, then blends them with roasted garlic and apple cider vinegar; even the fermented stems become a spicy chilli vinegar.",
    angles: ["A Peruvian scientist and chef running a zero-waste, circular-cooking Berlin producer.", "Upcycled, rescued-produce hot sauce: the sustainability angle for a business or eco desk.", "Fermented Jalapeño, a mild green sauce from six-week-fermented chillies, with nothing wasted."],
    photo: "/chilifest/makers/roots-radicals.jpg",
  },
  {
    id: "yak-thai",
    name: "Yak Thai",
    legalName: "",
    maker: "Chonticha Schopf",
    location: "Volkenschwand, Bavaria",
    track: "Seed to Sauce",
    flagship: "Namprik Sam Het",
    heat: "2–5/10",
    awards: "",
    story: "When a Thai confectioner moved to Germany with her husband, they couldn't find the genuine Thai flavours they missed, so they began making their own curry and chilli pastes in rural Bavaria, with dried chillies imported straight from Thailand. Nothing is toned down for the German market: the same fish sauce, shrimp paste and oyster sauce they used back home. Their Namprik Sam Het, a 'three-mushroom' chilli paste, is the umami-rich hero, as good as a dip as a cooking base.",
    angles: ["A Thai confectioner and her husband making additive-free curry and chilli pastes in rural Bavaria, nothing toned down for Germany.", "Namprik Sam Het, a 'three-mushroom' chilli paste, umami-rich and as good as a dip as a cooking base.", "A range from Khao Soi curry paste at 2/10 to Namprik Sam Het at 4-5, chillies imported from Thailand for real flavour."],
    photo: "/chilifest/makers/yak-thai.jpg",
  },
  {
    id: "dr-john-s-hot-sauce",
    name: "Dr. John's Hot Sauce",
    legalName: "",
    maker: "Albert Ortez",
    location: "Nürnberg, Franconia",
    track: "Hyperlocal",
    flagship: "Trippy Habanero Mango",
    heat: "7/10",
    awards: "",
    story: "Albert Ortez cooked a mango-habanero sauce as a one-off Christmas present for his brother, a self-confessed hot sauce addict. His brother lost it; then his friends wanted a bottle, then strangers were asking where to buy 'that mango habanero stuff.' A joke gift became Dr. John's, the Nürnberg brand Albert has run since 2020.",
    angles: ["A Nürnberg maker whose mango-habanero sauce started as a one-off Christmas gift for his hot-sauce-addict brother and became a brand.", "Trippy Habanero Mango at 7/10: fruity habanero pushed further with ripe mango, sweet and sharp with a heat that creeps up on you.", "A three-sauce range, from a fermented lime-zest 'Twisted' sriracha to a grill-built Carolina Reaper, out of Germany's chilli-friendly Franconia."],
    photo: "/chilifest/makers/dr-john-s-hot-sauce.jpg",
  },
  {
    id: "salsa-boy",
    name: "Salsa Boy",
    legalName: "",
    maker: "Sascha Mayer",
    location: "Berlin, DE",
    track: "Hyperlocal",
    flagship: "Salsa Boy 01",
    heat: "",
    awards: "",
    story: "A one-person Berlin project with a straight face and a bold claim printed on the label: 'Berlin's premium chilli sauce.' The sauce itself is fermented jalapeño and cayenne, finished with fresh lime.",
    angles: ["A one-person Berlin project making a big claim on the label.", "Single-maker premium positioning: 'Berlin's premium chilli sauce'.", "Fermented jalapeño, cayenne and lime, bottled in small runs in Berlin."],
    photo: "/chilifest/makers/salsa-boy.jpg",
  },
  {
    id: "julies-chili",
    name: "Julie's Chili",
    legalName: "",
    maker: "Julie",
    location: "Germany",
    track: "Flavour",
    flagship: "Yellow Habanero",
    heat: "3/10",
    awards: "",
    story: "After moving from Congo to Germany, Julie couldn't find the spice she grew up with, so she built her own line of sauces. She made this milder yellow habanero for her son's friends who found the red version too hot, and by their verdict it was a hit. Vegan, made with natural ingredients.",
    angles: ["A cook who moved from Congo to Germany and built her own line to replace the spice she couldn't find.", "A milder yellow habanero made for the next generation: her son's friends who found the red one too hot.", "Yellow Habanero at 3/10, vegan and flavour-led, the gentle end of a home-built range."],
    photo: "/chilifest/makers/julies-chili.jpg",
  },
];
